# Generated by Django 3.0.7 on 2020-07-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('education', models.CharField(blank=True, max_length=10000)),
                ('work', models.CharField(blank=True, max_length=10000)),
                ('skills', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
