# Generated by Django 3.0.4 on 2020-03-18 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('date_due', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date_due'],
            },
        ),
    ]
