# Generated by Django 3.0.4 on 2020-03-20 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_auto_20200320_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_create',
            field=models.DateField(default=datetime.date(2020, 3, 20)),
        ),
    ]
