# Generated by Django 3.0.7 on 2020-07-09 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_auto_20200322_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_create',
            field=models.DateField(default=datetime.date(2020, 7, 9)),
        ),
    ]
