# Generated by Django 3.0.7 on 2020-07-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0007_auto_20200709_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_create',
            field=models.DateField(default=datetime.date(2020, 7, 21)),
        ),
    ]
