# Generated by Django 3.0.7 on 2020-08-02 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0008_auto_20200721_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_create',
            field=models.DateField(default=datetime.date(2020, 8, 2)),
        ),
    ]
